# Generated by Django 5.2.8 on 2025-12-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(default=10, help_text='Сколько часов в среднем занимает прохождение курса', verbose_name='Продолжительность (часов)'),
        ),
    ]
