# Generated by Django 5.2.8 on 2025-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Если не отмечено, урок будет виден только преподавателю', verbose_name='Опубликован'),
        ),
    ]
